//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Programming_Interface.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaftyEngineer
    {
        public int SEID { get; set; }
        public string SEName { get; set; }
        public string SEPhone { get; set; }
        public string SEEmail { get; set; }
        public string SEAddress { get; set; }
        public Nullable<decimal> SESalary { get; set; }
        public string SEDesig { get; set; }
    }
}
